### ISSUE TITLE
Latest patch release increases MSRV

### ISSUE THREAD

**Issue by wezm** [rust-lang/libz-sys#101]
The use of [extended_key_value_attributes](https://github.com/rust-lang/rust/issues/78835) requires 1.54.0 or newer.

I don't see mention of a minimum supported Rust version in the README or Cargo.toml and note that CI tests on latest stable, beta, and nightly so perhaps this is not considered an issue but wanted to note the the latest patch release (1.1.8) breaks support for older Rust versions. The 1.1.6 release works at least as far back as 1.51.0.

Errors when compiling on 1.53.0:

https://gist.github.com/wezm/a46027bb12038bf396f00502eec112b7

**Comment by joshtriplett** [comment]
Thank you for catching this. (And sorry for the *very* long delay in responding. I've added a co-maintainer for this crate to help take better care of it. :) )

I had thought this crate documented an MSRV policy, but it indeed does not. I've added one, copied from the MSRV policy of the `flate2` crate.
