### ISSUE TITLE
closed！Thanks！

### ISSUE THREAD

**Issue by mindrock** [rust-lang/libz-sys#102]
Hi @snorp @mneumann @alexcrichton 
error: failed to run custom build command for `libz-sys v1.1.8` , with CLI command "cargo build --target=wasm32-wasi"

I want to compile this [repository](https://github.com/MediosZ/rust-mysql-simple/tree/mywasi),error was happened.i want to fix it with one days, always failed to build on macOS.rendering me unable to use cargo-update.

below detail error info:
> warning: error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-wasi"'
> error: failed to run custom build command for `libz-sys v1.1.8`
> error: failed to run custom build command for `openssl-sys v0.9.74`

_cargo --version：1.61.0
rustc --version：1.61.0
wasmtime: v0.37.0-x86_64-macos
wasmedge: version 0.10.0
x86_64-apple-darwin (installed)
OSX 12.4 intel-X86_

Here is the entire error message:
![Snipaste_2022-06-13_18-58-15](https://user-images.githubusercontent.com/10820997/173339473-cfcb1d9d-03f0-49a1-901e-3768fb885014.jpg)

**Comment by samdenty** [comment]
Hi mindrock how did you fix this?
