### ISSUE TITLE
build using windows-gnu on windows failed

### ISSUE THREAD

**Issue by WhatzGames** [rust-lang/libz-sys#135]
I tried to build starship.rs using their cargo install command but got the following error

```
error: failed to run custom build command for `libz-ng-sys v1.1.9`

Caused by:
  process didn't exit successfully: `C:\Users\...\AppData\Local\Temp\cargo-installWWt6vf\release\build\libz-ng-sys-b8b5ed917a8091c5\build-script-build_zng` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-gnu = None
  CMAKE_GENERATOR_x86_64_pc_windows_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-gnu = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-gnu = None
  CMAKE_x86_64_pc_windows_gnu = None
  HOST_CMAKE = None
  CMAKE = None

  --- stderr
  thread 'main' panicked at '
  no valid generator found for GNU toolchain; MSYS or MinGW must be installed

  build script failed, must exit now', C:\Users\okooijman\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Would I really have to get another toolchain for this?
Or is there any other possible fix?

**Comment by Byron** [comment]
Thanks for sharing! 

I don't think that this is necessarily an issue to resolve here as `libz-ng-sys` comes with a `cmake` based system, and that seems to want more tools to build. If anyone could do something about it, it *should* be the folks making [`zlib-ng`](https://github.com/zlib-ng/zlib-ng).

For completeness, `starship` pulls in `gitoxide`, which has been configured for maximum performance by default,  It can, however, also be built with a stock zlib which *might* be working for you.

Could you try the following?

```
cargo install --locked --no-default-features --features=battery,notify,gix-faster
```

If that doesn't work, I think it's better to [open an issue over at `starship`](https://github.com/starship/starship/issues) as it's possible to add a `starship` feature to build for maximum compatibility (and pure Rust, for that matter). I would happily contribute such a fix as well.

**Comment by WhatzGames** [comment]
Thanks for the help!
It worked now.

I'll ask if it at least can be noted in their wiki or something.
