### ISSUE TITLE
Size regressions in level-9 compression in 1.1.9

### ISSUE THREAD

**Issue by thaliaarchi** [rust-lang/libz-sys#137]
I noticed size regressions in level-9 compression size between libz-ng-sys 1.1.8 and 1.1.9.

Commit f60e16b8dc6fb71dbeb715f741b901475a1c2672 (2023-04-02) introduced the regression by bumping the zlib-ng submodule from
https://github.com/zlib-ng/zlib-ng/commit/856884022cc7202b159ba76c8e89bb1d9f7300d5 (2022-05-25) to 2.0.7 (https://github.com/zlib-ng/zlib-ng/commit/a583e215afa2356e23b418efa871a1cc4348702a, 2023-03-17). Then, smuggled with an unremarkable refactor, commit cdcca212cb0f4372e9c241286e8ea06d0b28826c (2023-05-30) changes the version again without explanation, but to an older one than before, https://github.com/zlib-ng/zlib-ng/commit/43dbfd6709fb3a8028430ea30f3da88fbeb3ced9 (2022-02-24), which fixes the regression. I'm not sure the reasoning for that latter commit changing the submodule.

I wasn't able to pinpoint where exactly zlib-ng changed this behavior with compression level 9, because the 2.0.x and 2.1.x branches are discontinuous and so don't work with a git bisect, but zlib-ng 2.1.2 or 2.1.3 fix the issue for me.

If https://github.com/rust-lang/libz-sys/pull/133 were merged, that would fix this.

**Comment by Byron** [comment]
Thanks for letting us know and for figuring out a cure :). I am trying to get #133 merged and push it towards a new release.

**Comment by thaliaarchi** [comment]
Thank you @Byron! The 1.1.10 release fixes my issue.
