### ISSUE TITLE
bump patch for crate

### ISSUE THREAD

**Issue by ognevnydemon** [rust-lang/libz-sys#166]
just a suggestion, as in msys2 we want to have fix for `*-gnullvm` target applied at stable so we can update it for needed packages (e.g. starship)

**Comment by Byron** [comment]
Is this something you have experience with and can attempt? Maybe it's as easy as updating a submodule. Even if not, maybe it's an experience worth having as I am typically relying on update-contributions for this and am happy to get these released as often as they happen.

**Comment by ognevnydemon** [comment]
we need an update to compile the crate for `aarch64-pc-windows-gnullvm` target (MSYS2). an old version included `arm64_neon.h` which is MSVC only. so there was a build failure

**Comment by Byron** [comment]
> I can contribute if needed only tomorrow

Yes, please feel free to contribute the update. Unless I am missing something, I'd expect it to pass CI without hitches, and thus is eligible for a release.

**Comment by mati865** [comment]
The update has already happened in https://github.com/rust-lang/libz-sys/pull/162
It's just not published as a new version and that would be the only necessary action.

**Comment by Byron** [comment]
Even better! Then it would be best if someone could create a PR with the version change so I can merge it and create a new release. If I would create that PR I can't review it myself which has the potential for delays.
