### ISSUE TITLE
failed to run custom build command for `libz-sys v1.1.16`

### ISSUE THREAD

**Issue by habibsaky** [rust-lang/libz-sys#192]
I am trying to install mod kit but aim facing error here
--failed to run custom build command for `libz-sys v1.1.16`
cargo install --git https://github.com/nanoporetech/modkit.git

**Comment by Byron** [comment]
Without a log, one cannot know for sure. Typically this fails because dev-tools like `cmake` aren't available. 
Please feel free to provide more information.
