### ISSUE TITLE
zlib-ng-sys is not updated in crates

### ISSUE THREAD

**Issue by JakubOnderka** [rust-lang/libz-sys#223]
Hello,

latest version on crates.io of [`libz-sys`](https://crates.io/crates/libz-sys) is v1.1.20, but latest version of [`libz-ng-sys`](https://crates.io/crates/libz-ng-sys/) is v1.1.16. 

Can you please update `libz-ng-sys` on crates and maybe use GitHub Actions to publish crates to crates.io, so both versions will be always sync?

**Comment by Byron** [comment]
Apologies, I wasn't aware that this is a requirement.

Historically, `libz-ng-sys` releases where made occasionally after its code was updated, and the version was chosen to be in sync with `libz-sys`, possibly skipping versions. Doing so certainly has the advantage of knowing that both are about the same age.

A new version was just published: https://crates.io/crates/libz-ng-sys/1.1.20.
Also I will see to keeping both in sync.
