### ISSUE TITLE
Version 1.0.22 doesn't compile with Rust 1.25

### ISSUE THREAD

**Issue by asajeffrey** [rust-lang/libz-sys#41]
We're getting build failures on travis caused by using features which were unstable in Rust 1.25, e.g. https://travis-ci.org/servo/mozjs/jobs/429237190.

**Comment by alexcrichton** [comment]
This crate currently supports the last two stable releases officially, but support for older versions is always welcome through PRs!

**Comment by joshtriplett** [comment]
There hasn't been any activity on this issue in nearly two years. If there's still, today, a specific use case to build on some specific older version of rustc, please open a separate issue.
