### ISSUE TITLE
pkg_config always adds system-wide path to rustc-link-search

### ISSUE THREAD

**Issue by rinon** [rust-lang/libz-sys#49]
Could we get `.print_system_libs(false)` added to the pkg_config `Config`? libz-sys is far down the dependency chain from my package and adds `/usr/lib` to the search path. This means that the linker grabs another library we want to link against from `/usr/lib` instead of our non-system search path that we add using `rustc-link-search`.

This is the same basic issue as https://github.com/sfackler/rust-openssl/issues/447 and https://github.com/alexcrichton/pkg-config-rs/issues/11

Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report! I don't think the answer is to not print out `-lz`, but to just not print out `-L /usr/...`. Currently I don't think there's an easy way to do that.

**Comment by rinon** [comment]
If I understand `Config.print_system_libs` correctly, it just sets `PKG_CONFIG_ALLOW_SYSTEM_LIBS=1` for `pkg-config`, which just skips printing `-L /usr/lib` according to the man page:
> PKG_CONFIG_ALLOW_SYSTEM_LIBS
Don't strip -L/usr/lib out of libs

**Comment by alexcrichton** [comment]
Ok seems like it just needs a PR then!

**Comment by joshtriplett** [comment]
Merged.
