### ISSUE TITLE
Yank breaking versions with "*" deps

### ISSUE THREAD

**Issue by kornelski** [rust-lang/libz-sys#57]
An old version of `libz-sys` has dependencies specified with `"*"` version requirement (`libc = "*"`, `pkg-config = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because this old version of `libz-sys` is unusable and may cause problems for Cargo, I suggest yanking it:

```bash
cargo yank --vers 0.0.1
```

**Comment by joshtriplett** [comment]
It looks like there are multiple old versions of libz-sys that have unversioned dependencies: 0.0.1 has an unversioned dependency on pkg-config, and 0.1.3 has an unversioned dependency on libc. Are you suggesting yanking both?

**Comment by kornelski** [comment]
Yes.

**Comment by joshtriplett** [comment]
Done.
