### ISSUE TITLE
Could the readme also point to pure rust alternatives?

### ISSUE THREAD

**Issue by gilescope** [rust-lang/libz-sys#62]
Hi Alex, 

Now that fancy is available as an alternative to ongi for regex, the next most widely used crate that doesn't just easily build on windows is this one (in my very non-generalized experience). Here's an example of it not working out of the box:

```
note, vcpkg did not find zlib: Could not find Vcpkg tree: No vcpkg.user.targets found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'
```

Can we let people know in the readme that there are pure rust alternatives that might well have less build issues?
I'm pretty sure you have a much better idea which one (ones) might be closest.
Anyway it would be great to have some pointers to the debate / options out there on the readme so that people don't choose this crate without considering the options.

With kind regards,

Giles

**Comment by joshtriplett** [comment]
Done, and thanks for the suggestion.
