### ISSUE TITLE
failed to install cargo-generate

### ISSUE THREAD

**Issue by ty-russ** [rust-lang/libz-sys#77]
The following warnings were emitted during compilation:

warning: cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
warning: cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

error: failed to run custom build command for `libz-sys v1.1.2`

Caused by:
  process didn't exit successfully: `C:\Users\user\AppData\Local\Temp\cargo-install9c9Xjd\release\build\libz-sys-1d114701a840fc80\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=ZLIB_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=ZLIB_STATIC
  cargo:rerun-if-env-changed=ZLIB_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  TARGET = Some("x86_64-pc-windows-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-pc-windows-gnu")
  CC_x86_64-pc-windows-gnu = None
  CC_x86_64_pc_windows_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-gnu = None
  CFLAGS_x86_64_pc_windows_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "src/zlib" "-o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install9c9Xjd\\release\\build\\libz-sys-aefdef1f6450ae45\\out\\build\\src/zlib/adler32.o" "-c" "src/zlib/adler32.c"
  cargo:warning=cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
  exit code: 1
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "src/zlib" "-o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install9c9Xjd\\release\\build\\libz-sys-aefdef1f6450ae45\\out\\build\\src/zlib/compress.o" "-c" "src/zlib/compress.c"
  cargo:warning=cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
  exit code: 1

  --- stderr

  error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "src/zlib" "-o" "C:\\Users\\user\\AppData\\Local\\Temp\\cargo-install9c9Xjd\\release\\build\\libz-sys-aefdef1f6450ae45\\out\\build\\src/zlib/adler32.o" "-c" "src/zlib/adler32.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).      

warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
warning: cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

The following warnings were emitted during compilation:

warning: cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
warning: cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

error: failed to compile `cargo-generate v0.6.0`, intermediate artifacts can be found at `C:\Users\user\AppData\Local\Temp\cargo-install9c9Xjd`

Caused by:
  build failed
PS D:\Projects\playground\RUST>

**Comment by lygamac** [comment]
gcc only works with 32-bit rust compiler. Use MSVC instead.

https://github.com/alexcrichton/cc-rs#compile-time-requirements
