### ISSUE TITLE
Faile to build! libz-sys 1.1.3, use nightly-x86_64-pc-windows-gnu toolchain

### ISSUE THREAD

**Issue by TQLeung** [rust-lang/libz-sys#82]
nightly-x86_64-pc-windows-msvc can build success
but nightly-x86_64-pc-windows-gnu is faile! any version

error: failed to run custom build command for `libz-sys v1.1.3`

**Comment by TQLeung** [comment]
@steveklabnik @snorp @mneumann @skade how can i fix it?

**Comment by tbu-** [comment]
Needs error messages. Since the issue is quite old and none are provided, it can probably be closed.
