### ISSUE TITLE
Does not use system dylib when cross-compiling on macOS

### ISSUE THREAD

**Issue by kornelski** [rust-lang/libz-sys#84]
macOS has fat binary dylibs with executable code for multiple architectures. When cross-compiling between macOS on x86 and ARM, all system libraries are usable on both architectures, including libz.1.dylib.

The current logic gives up on system zlib when [`target != host`](
https://github.com/rust-lang/libz-sys/blob/6b12e9a37bae1a444aaa1a11248c5b0e555869b4/build.rs#L73), which causes unnecessary static linking when the target and host are `x86_64-apple-darwin` and `aarch64-apple-darwin`.

**Comment by kornelski** [comment]
Detection whether `/usr/lib/libz.dylib` is actually available as a fat binary is unfortunately complicated, because since macOS 11 all system libraries are part of a monolithic shared cache, and don't exist as individual files in the file system any more (library paths are merely magic keys for lookup in system cache). Apple recommends checking their existence by running `dlopen`, but that's highly problematic for cross-compilation. For libz it may be enough to just assume it's present.

**Comment by kornelski** [comment]
Similar issue when cross-compiling to iOS. iOS has libz shared library.

**Comment by glandium** [comment]
I don't think this is fixed. As a matter of fact I have a cross-compile job that ends up compiling zlib (and failing, because it's using clang trunk, which broke building zlib < 1.3.1).

**Comment by Byron** [comment]
There is now [v1.1.15 of `libz-sys`](https://crates.io/crates/libz-sys/1.1.15) with `libz` 1.3.1 in case this changes anything.
