### ISSUE TITLE
could not compile libz-sys because libc::off_t not found

### ISSUE THREAD

**Issue by gouthamreddy09** [rust-lang/libz-sys#91]
Hello,
I tried compiling my project with Miniflare but it fails with this error.
I'm using Windows Sub system Linux 2.0,Ubuntu 20.04.
![error](https://user-images.githubusercontent.com/32016010/157512367-3b6eb438-b808-4411-8566-a407364f5df7.png)

**Comment by joshtriplett** [comment]
Fix merged, will be in the next release.
